kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: converter-nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
